# THIS FILE HAS BEEN AUTOGENERATED. To update:
# 1. modify the `_deps` dict in setup.py
# 2. run `make deps_table_update``
deps = {
    "python": "python>=3.10.0",
    "numpy": "numpy>=1.26.0,<2.0.0",
    "pandas": "pandas>=2.2.2",
    "tqdm": "tqdm>=4.66.5",
    "oneflow": "oneflow>=0.9.0",
    "pytest": "pytest>=8.3.2",
    "pytest-xdist": "pytest-xdist>=3.6.1",
    "torch": "torch<2.4.0,>=2.2.0",
    "ruff": "ruff>=0.5.7",
    "bitsandbytes": "bitsandbytes>=0.43.3",
    "nvidia-cudnn-cu12": "nvidia-cudnn-cu12<9.0.0.0,>=8.9.0.0",
    "safetensors": "safetensors>=0.4.0",
    "sentencepiece": "sentencepiece>=0.2.0",
    "tokenizers": "tokenizers>=0.11.6",
}
